### ISSUE TITLE
SOC4 codes do not have lookup for Major, Sub-Major or Minor groups apart from first instance of each

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/WNYCC-LSIP#22]
These are the only major, sub-major and minor groups

```
     major_group  sub_major_group  minor_group  unit_group                                   group_title
0              1             <NA>         <NA>        <NA>      MANAGERS, DIRECTORS AND SENIOR OFFICIALS
1              1               11         <NA>        <NA>              CORPORATE MANAGERS AND DIRECTORS
2              1               11          111        <NA>         Chief Executives and Senior Officials
```

It would also be useful to normalise the names of columns:

```
Major Group => major_group
Sub-Major Group => sub_major_group
Minor Group => minor_group
Unit   Group => unit_group
Group Title => group_title
```

There may also be a better shape to put this in for lookup, but I can do this as part of the processing pipeline if the issue above is fixed

```
soc4_code,major_group_name,sub_major_group_name,minor_group_name,unit_group_name
```

**Comment by gilesdring** [comment]
Ignore parts two and three of the above - we can look at those later. I've got code which reshapes them to the state I need.

**Comment by gilesdring** [comment]
I think these might be here, but you're not resetting the lower level values when the top one cycles

```
1,12,125,1259,Managers and proprietors in other services n.e.c.
2,12,125,1259,PROFESSIONAL OCCUPATIONS
2,21,125,1259,"SCIENCE, RESEARCH, ENGINEERING AND TECHNOLOGY PROFESSIONALS"
2,21,211,1259,Natural and Social Science Professionals
2,21,211,2111,Chemical scientists
```

**Comment by gilesdring** [comment]
Have managed to work around this (removing erroneous sub-major, minor and unit names and reshaped for lookup

**Comment by ChristianSpence** [comment]
Error in original code identified. Will update the data file. Thinking about what principles we might use to determine shape of multilevel lookups like these, wondering if this format would be more appropriate

```
level,soc2010_code,soc4_description
1,1,"MANAGERS, DIRECTORS AND SENIOR OFFICIALS"
2,11,CORPORATE MANAGERS AND DIRECTORS
3,111,Chief Executives and Senior Officials
4,1115,Chief executives and senior officials
4,1116,Elected officers and representatives
3,112,Production Managers and Directors
4,1121,Production managers and directors in manufacturing
```

**Comment by ChristianSpence** [comment]
@gilesdring Before committing the update to the original, here's the proposed output to agree before I overwrite.
[soc2010 v2.csv](https://github.com/open-innovations/WNYCC-LSIP/files/10909943/soc2010.v2.csv).

All other formats we've discussed are also available, but I don't want to interrupt already written workflows so let me know which you want.
