### ISSUE TITLE
Confirm a definition within A-level data

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/WNYCC-LSIP#23]
All state-funded schools _vs_ all state-funded schools and colleges

**Comment by ChristianSpence** [comment]
@gilesdring @luke-strange was this question related to A-level or FE destination data? Can't see anything in the A-level, but here is an excerpt from the FE destination metadata which I think answers your question:

> 2. Total state-funded mainstream schools and colleges covers all state-funded mainstream schools, academies, free schools, city technology colleges (CTCs), sixth-forms and other and FE sector colleges. Excludes alternative provision, special schools, other government department funded colleges and independent schools.
> 3. All other education destinations include school sixth forms, sixth-form colleges, independent schools, specialist post-16 institutions, special schools and education combination destinations.
> 4. State-funded mainstream schools also includes city technology colleges (CTCs). Figures for this institution type are not shown separately in the table. Excludes pupil referral units (PRUs), alternative provision (AP), hospital schools, maintained and non-maintained special schools, independent schools, independent special schools and independent schools approved to take pupils with special educational needs (SEN).
> 5. State-funded mainstream colleges excludes other government department funded colleges.

**Comment by gilesdring** [comment]
Thanks - I think we're OK to leave #4 as is on this basis. Closing this as done!

**Comment by gilesdring** [comment]
This is relevant to #7
