### ISSUE TITLE
Create version of FE & Skills Geography excluding Army apprenticeships

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/WNYCC-LSIP#32]
https://open-innovations.github.io/WNYCC-LSIP/metadata/fe/Further%20education%20and%20skills%20geography%20-%20detailed%20summary/

**Comment by ChristianSpence** [comment]
@gilesdring @luke-strange I can't see any army providers in the provider level data we have for FE. Will keep investigating but not sure yet that we can exclude these as we can't identify them.

**Comment by ChristianSpence** [comment]
Have found the separate listing of Army apprentices, but they're in a separate dataset solely for apprenticeships and traineeships. Know it's late in the day but feel we should probably include this. Happy to do the heavy lift on the data prep. We need 10 minutes to discuss, @gilesdring

**Comment by ChristianSpence** [comment]
@gilesdring @luke-strange Have added apprenticeships specific data into `data/csv/apprenticeships` at local authority, apprenticeship level (inc. total), SSA T1 (subject) (inc. total).

Lots of suppression in the data (low = >0 & <5), but may be useful to have for the local authority totals and where there is at least some data.

NB this is 2022/23 data (so year so far) - not comparable with the rest (which 21/22) but it's the only year we've got data that's at LA and subject level that I can manually build a table for. (We can get earlier years but, as it's preformatted and is cut by age, sex and ethnicity, >90% of data rows are suppressed. Useless!)

**Comment by ChristianSpence** [comment]
Moving back to "ready" for picking up for a page build

**Comment by gilesdring** [comment]
I’ll close this one and either create a new one or mention in the open apprentices ticket should one exist.

**Comment by gilesdring** [comment]
Aha - I see you’ve done this in #44

**Comment by luke-strange** [comment]
Need to discuss this off the back of LSIP meeting.
