### ISSUE TITLE
check the stats on FE page

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/WNYCC-LSIP#35]
need to check headline stats and verify them, make sure they're roughly correct. possibly round to nearest 1k

**Comment by gilesdring** [comment]
See humanise filter in Leeds 2023. https://github.com/open-innovations/leeds-2023/blob/640c996884c0194ace112b4b5624adc7b8fc66f8/_config.js#L149-L162

**Comment by luke-strange** [comment]
@gilesdring can't seem to implement humanise filter. Not getting any errors but doesn't seem to work.
