### ISSUE TITLE
Fix NA value replacement issue.

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/WNYCC-LSIP#40]
Currently all NA values get replaced to the same thing. In some files we need to set 'NA' to 0 and 'low' to 2.

**Comment by gilesdring** [comment]
I suspect that something like this might work:

```python
data.col[data.col == 'low'] = '2'
data.col = pd.to_numeric(data.col, errors='coerce')
```

Sample code below:

```python
s = pd.Series(['10', '20', 'low', 'NA'])
s[s=='low'] = 2
s = pd.to_numeric(s, errors='coerce')
```

`s` ends up as 
```
0    10.0
1    20.0
2     2.0
3     NaN
dtype: float64
```

**Comment by luke-strange** [comment]
solved using data = data.replace(['low'], '2'). 

Then pandas automatically reads 'NA' as NaN (see below)


![Image](https://user-images.githubusercontent.com/92686634/228177128-cbb3d159-6b5e-49bf-b2a5-7a402a10bb39.png)
