### ISSUE TITLE
Add 16-18 apprenticeship data

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/WNYCC-LSIP#41]
code is written, need to re-run and then visualise. If someone else picks this up just ask me to show you what I have done so far.

**Comment by gilesdring** [comment]
May need to create a new page to display some of the apprenticeship and traineeship data that @ChristianSpence sourced in #32

**Comment by luke-strange** [comment]
Agree with @gilesdring that an additional page would be useful. There is some data on each page for apprenticeships, and this sitll needs to be reviewed in relation to #39

**Comment by gilesdring** [comment]
Effort on apprenticeship data now tracked in #44
