### ISSUE TITLE
Add feedback email link to footer of page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/WNYCC-LSIP#47]
Link should target skills at wnychamber and include a subject / body identifying the page the feedback is being sent from

**Comment by ChristianSpence** [comment]
We have a rendering issue with this; re-opening.

![image](https://user-images.githubusercontent.com/5487421/229729260-69bcb2c9-6d0c-4f76-9b23-592835e34930.png)

**Comment by ChristianSpence** [comment]
From Paul:

"Can we check how this looks on mobile pls?

On my phone (google pixel & Firefox & chrome) the footer is blocking scrolling and bottom of main page."

**Comment by gilesdring** [comment]
Opened alternative ticket covering the footer #54
