### ISSUE TITLE
Visualise BRES and UKBC data

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/WNYCC-LSIP#50]
Visualise:

* business size (micro to large) over time by Local Authority / for region (from UKBC data)
* Industry sector for most recent year (from BRES data)

Both files in this directory: https://github.com/open-innovations/WNYCC-LSIP/tree/main/data/csv/nomis

**Comment by luke-strange** [comment]
The business sizes over time will need to be shown on different graphs due to the scaling. This is what it looks like with them all on the same page.


![Image](https://user-images.githubusercontent.com/92686634/230424858-23436696-2e1b-4009-9870-e35bf5e4cc3d.png)

**Comment by luke-strange** [comment]
In relation to above, I think a graph of percentage change would work here, enabling direct comparison between business sizes. then a table of the actual values alongside. I will add this next week

**Comment by luke-strange** [comment]
BRES data will be added as a tree map once @gilesdring has finished the cleaner version of tree maps integrated with OI lume charts.

**Comment by luke-strange** [comment]
PCT change figure done. Need to add treemap in once it's ready in the lume charting library.

**Comment by ChristianSpence** [comment]
Do we still need to add treemap or similar for BRES data?

**Comment by luke-strange** [comment]
@ChristianSpence it's done, is just on a separate branch at the moment as we didn't want to push anything new before your meeting yesterday.
