### ISSUE TITLE
Add information about date range to each page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/WNYCC-LSIP#51]

**Comment by gilesdring** [comment]
May need to discuss with @ChristianSpence - possibly need to update metadata content.

**Comment by ChristianSpence** [comment]
@gilesdring I think that all DfE and HESA (though the latter not currently in use) datasets contain a date dimension which should be clear, but shout if not and I'll ensure one is added. Same applies to ONS data we're extracting from NOMIS.

**Comment by ChristianSpence** [comment]
Perhaps also worth noting that they did like the idea of time series availability where it may possible. Challenging on the detailed charts, but perhaps we could do something with the headline numbers?

**Comment by gilesdring** [comment]
We're looking at this for the BRES etc data. Should provide a pattern.

**Comment by luke-strange** [comment]
I have automated some of the dates to appear on the page, will need to do this for all pages.
