### ISSUE TITLE
Add visualisation of survey data

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/WNYCC-LSIP#70]

**Comment by luke-strange** [comment]
@ChristianSpence do you have any particular things you'd like to visualise? which dimensions do we want to split by.

**Comment by ChristianSpence** [comment]
Let's pick this up tomorrow (wed 17-05) with the other things

**Comment by luke-strange** [comment]
Need to discuss data anonymity - (I have made notes offline on this)

**Comment by luke-strange** [comment]
Initial vis is done, need to discuss what else we want on there.
